os:
  - linux
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:apokluda/boost1.53
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - sudo apt-get install libboost1.53-all-dev
  - sudo apt-get install libxmlrpc-c++4-dev libxml2-dev libjsoncpp-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
script:
  - mkdir build
  - cd build
  - cmake -DJSONCPP_LIB_BUILD_SHARED=ON .. && make
branches:
  only:
    - master
    - develop
notifications:
  recipients:
    - jon@monetas.net
  email:
    on_success: change
    on_failure: always
